/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.87
 * Generated at: 2024-02-07 06:41:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.KhachHang;
import model.KhachHang;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1707276739909L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1707287855180L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.KhachHang");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1,shrink-to-fit=no\">\r\n");
      out.write("    <title>Bookstore</title>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <!-- Header -->\r\n");
      out.write("    <!-- NavBar -->\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1,shrink-to-fit=no\">\r\n");
      out.write("    <title>Bookstore</title>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("      ");

    	String url = request.getScheme() + "://" + request.getServerName()+ ":"+request.getServerPort() + request.getContextPath(); 
    
      out.write("\r\n");
      out.write("    <!-- NavBar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-body-tertiary\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"https://titv.vn/wp-content/uploads/2022/08/Screenshot-2023-01-29-230321.png\"\r\n");
      out.write("            alt=\"Bootstrap\"\r\n");
      out.write("            height=\"24\"\r\n");
      out.write("          />\r\n");
      out.write("        </a>\r\n");
      out.write("        <button\r\n");
      out.write("          class=\"navbar-toggler\"\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          data-bs-toggle=\"collapse\"\r\n");
      out.write("          data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("          aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("          aria-expanded=\"false\"\r\n");
      out.write("          aria-label=\"Toggle navigation\"\r\n");
      out.write("        >\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\"\r\n");
      out.write("                >Trang chur</a\r\n");
      out.write("              >\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">Combo giảm giá</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("              <a\r\n");
      out.write("                class=\"nav-link dropdown-toggle\"\r\n");
      out.write("                href=\"#\"\r\n");
      out.write("                role=\"button\"\r\n");
      out.write("                data-bs-toggle=\"dropdown\"\r\n");
      out.write("                aria-expanded=\"false\"\r\n");
      out.write("              >\r\n");
      out.write("                Thể loại\r\n");
      out.write("              </a>\r\n");
      out.write("              \r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Quần Jean</a></li>\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Áo Thun</a></li>\r\n");
      out.write("                <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Áo sơ mi</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link disabled\" aria-disabled=\"true\">Hết hàng</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("            <div >\r\n");
      out.write("              <input\r\n");
      out.write("              class=\"form-control me-2\"\r\n");
      out.write("              type=\"search\"\r\n");
      out.write("              placeholder=\"Nội dung tìm kiếm\"\r\n");
      out.write("              aria-label=\"Search\"\r\n");
      out.write("            />\r\n");
      out.write("            <button class=\"btn btn-outline-success\" type=\"submit\">\r\n");
      out.write("              Tìm\r\n");
      out.write("            </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <!-- Login Button -->\r\n");
      out.write("              ");

              	Object obj = session.getAttribute("khachHang");
              	KhachHang khachHang = null;
              	if(obj != null)
              		khachHang = (KhachHang)obj;
              	
              	if(khachHang == null) {
              
      out.write("\r\n");
      out.write("              <a href=\"khachhang/login.jsp\" class=\"btn btn-primary\" style=\"white-space: nowrap;\" >\r\n");
      out.write("                Đăng nhập\r\n");
      out.write("              </a>\r\n");
      out.write("              ");
} else { 
      out.write("\r\n");
      out.write("                <!-- dropdown menu -->\r\n");
      out.write("                  <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 bg-infor\" >\r\n");
      out.write("                    <li class=\"nav-item dropdown dropstart\">\r\n");
      out.write("                      <a href=\"#\" class=\"nav-link dropdown-toggle\" aria-expanded=\"false\"\r\n");
      out.write("                      role=\"button\" data-bs-toggle=\"dropdown\">Tài khoản</a>\r\n");
      out.write("	                      <ul class=\"dropdown-menu\">\r\n");
      out.write("	                        <li><a class=\"dropdown-item\" href=\"#\">Đơn hàng của tôi</a></li>\r\n");
      out.write("	                        <li><a class=\"dropdown-item\" href=\"#\">Thông báo</a></li>\r\n");
      out.write("	                        <li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khachhang/update.jsp\">Thay đổi thông tin</a></li>\r\n");
      out.write("	                        <li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khachhang/changePassword.jsp\">Đổi mật khẩu</a></li>\r\n");
      out.write("	                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("	                        <li><a class=\"dropdown-item\" href=\"");
      out.print(url );
      out.write("/khach-hang?hanhDong=log-out&\">Thoát tài khoản</a></li>\r\n");
      out.write("	                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                \r\n");
      out.write("                <!-- <div class=\"row text-center\" style=\"margin-left: 0.25em;\">\r\n");
      out.write("                  <div class=\"row\">Xin chào <b>");
      out.print(khachHang.getTenDangNhap() );
      out.write("</b><br></div>\r\n");
      out.write("                  <div class=\"row\"><a style=\"white-space: nowrap;\" href=\"log-out\">\r\n");
      out.write("                    Đăng xuất\r\n");
      out.write("                  </a></div>                \r\n");
      out.write("                </div> -->\r\n");
      out.write("              ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- End NavBar -->");
      out.write("\r\n");
      out.write("    <!-- End NavBar -->\r\n");
      out.write("    <!-- End Header -->\r\n");
      out.write("    <!-- Page content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- Menu left -->\r\n");
      out.write("        <div class=\"col-lg-3\">\r\n");
      out.write("          <div class=\"list-group\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"#\"\r\n");
      out.write("              class=\"list-group-item list-group-item-action\"\r\n");
      out.write("              aria-current=\"true\"\r\n");
      out.write("            >\r\n");
      out.write("              Thời trang nam\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"list-group-item list-group-item-action\"\r\n");
      out.write("              >Thời trang nữ</a\r\n");
      out.write("            >\r\n");
      out.write("            <a href=\"#\" class=\"list-group-item list-group-item-action\"\r\n");
      out.write("              >Dành cho bé</a\r\n");
      out.write("            >\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--End Menu left -->\r\n");
      out.write("        <!-- Slider and Products  -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-lg-9 \">\r\n");
      out.write("			<!-- slider -->\r\n");
      out.write("			<div id=\"carouselExample\" class=\"carousel slide\">\r\n");
      out.write("				<div class=\"carousel-inner\">\r\n");
      out.write("				  <div class=\"carousel-item active\">\r\n");
      out.write("					<img src=\"img/slider/1.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"img/slider/2.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				  <div class=\"carousel-item\">\r\n");
      out.write("					<img src=\"img/slider/3.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("				  </div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"prev\">\r\n");
      out.write("				  <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				  <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExample\" data-bs-slide=\"next\">\r\n");
      out.write("				  <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("				  <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("				</button>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <!--End Slider -->\r\n");
      out.write("			  <!-- Product -->\r\n");
      out.write("			  <div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/product/1.png\" alt=\"\" height=\"250px\" class=\"card-img-top\"></a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h4 class=\"card-title\">\r\n");
      out.write("								<a href=\"#\">Aó thun Pro-S1</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<h5>50.000VND</h5>\r\n");
      out.write("							<p class=\"card-text\">Sản phẩm thoáng mát, màu sắc tốt</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-footer\">\r\n");
      out.write("							<small class=\"text-muted\">&#9733; &#9733;&#9733;&#9733;&#9734</small>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/product/2.png\" alt=\"\" height=\"250px\" class=\"card-img-top\"></a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h4 class=\"card-title\">\r\n");
      out.write("								<a href=\"#\">Aó thun Pro-S1</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<h5>50.000VND</h5>\r\n");
      out.write("							<p class=\"card-text\">Sản phẩm thoáng mát, màu sắc tốt</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-footer\">\r\n");
      out.write("							<small class=\"text-muted\">&#9733; &#9733;&#9733;&#9733;&#9734</small>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("					<div class=\"card h-100\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/product/3.png\" alt=\"\" height=\"250px\" class=\"card-img-top\"></a>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h4 class=\"card-title\">\r\n");
      out.write("								<a href=\"#\">Aó thun Pro-S1</a>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<h5>50.000VND</h5>\r\n");
      out.write("							<p class=\"card-text\">Sản phẩm thoáng mát, màu sắc tốt</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-footer\">\r\n");
      out.write("							<small class=\"text-muted\">&#9733; &#9733;&#9733;&#9733;&#9734</small>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			  <!-- End Product -->\r\n");
      out.write("		</div>\r\n");
      out.write("		        <!--End Slider and Products  -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<!-- End Page content -->\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1,shrink-to-fit=no\">\r\n");
      out.write("    <title>Bookstore</title>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </head>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("	<footer class=\"py-3 my-4\">\r\n");
      out.write("		<ul class=\"nav justify-content-center border-bottom pb-3 mb-3\">\r\n");
      out.write("		  <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text-body-secondary\">Home</a></li>\r\n");
      out.write("		  <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text-body-secondary\">Features</a></li>\r\n");
      out.write("		  <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text-body-secondary\">Pricing</a></li>\r\n");
      out.write("		  <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text-body-secondary\">FAQs</a></li>\r\n");
      out.write("		  <li class=\"nav-item\"><a href=\"#\" class=\"nav-link px-2 text-body-secondary\">About</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<p class=\"text-center text-body-secondary\">© 2023 Company, Inc</p>\r\n");
      out.write("	  </footer>");
      out.write("\r\n");
      out.write("	    <!-- End Footer -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
